- name: Deploying to tomcat server
  hosts: tomcat01
  become: yes
  tasks:
  - name: Copying the .war file to the tomcat server location
    ansible.builtin.copy:
      src: target/hello-world.war
      dest: /var/lib/tomcat9/webapps/
    
